# fly.toml app configuration file generated for ton-app on 2025-05-07T14:56:03+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'ton-app'
primary_region = 'cdg'

[build]
  dockerfile = 'Dockerfile'

[env]
  MONGO_URI = 'mongodb://user:password@...:27017'

[[services]]
  protocol = 'tcp'
  internal_port = 80

  [[services.ports]]
    port = 80
    handlers = ['http']

  [[services.ports]]
    port = 443
    handlers = ['tls', 'http']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
